"""add evaluations

Revision ID: 5f2ab23b9eac
Revises: 41ddc6f727fb
Create Date: 2026-09-27 23:25:47.760719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2ab23b9eac'
down_revision: Union[str, Sequence[str], None] = '41ddc6f727fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='evaluationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Enum('good', 'ok', 'should_improve', 'bad', 'insufficient_data', name='rating', native_enum=False, length=30), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=True),
    sa.Column('answered_correctly', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Enum('advance', 'hold', 'reject', name='recommendation', native_enum=False, length=30), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_evaluations_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('interview_id', name=op.f('uq_evaluations_interview_id'))
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_rating'), ['rating'], unique=False)

    op.create_table('question_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_summary', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Enum('correct', 'partially_correct', 'incorrect', 'unanswered', 'not_applicable', name='verdict', native_enum=False, length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_question_assessments_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_assessments'))
    )
    with op.batch_alter_table('question_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_assessments_evaluation_id'), ['evaluation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_assessments_evaluation_id'))

    op.drop_table('question_assessments')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_rating'))

    op.drop_table('evaluations')
    # ### end Alembic commands ###
