"""initial schema

Revision ID: 41ddc6f727fb
Revises: 
Create Date: 2026-09-27 20:15:23.957117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ddc6f727fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_name', sa.String(length=200), nullable=False),
    sa.Column('candidate_email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('resume_filename', sa.String(length=255), nullable=False),
    sa.Column('resume_path', sa.String(length=500), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('parsed_resume', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_progress', 'completed', 'abandoned', 'expired', name='interviewstatus', native_enum=False, length=30), nullable=False),
    sa.Column('end_reason', sa.Enum('time_limit', 'candidate_ended', 'disconnected', 'error', 'server_restart', name='endreason', native_enum=False, length=30), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('tts_voice', sa.String(length=100), nullable=True),
    sa.Column('stt_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_candidate_email'), ['candidate_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_status'), ['status'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_events_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_interview_id'), ['interview_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.Enum('greeting', 'response', 'closing', name='llmpurpose', native_enum=False, length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('request_messages', sa.JSON(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('finish_reason', sa.String(length=30), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_llm_calls_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_interview_id'), ['interview_id'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('interviewer', 'candidate', name='speaker', native_enum=False, length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('was_interrupted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_turns_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turns')),
    sa.UniqueConstraint('interview_id', 'seq', name=op.f('uq_turns_interview_id'))
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_interview_id'), ['interview_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_interview_id'))

    op.drop_table('turns')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_interview_id'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_interview_id'))

    op.drop_table('events')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_status'))
        batch_op.drop_index(batch_op.f('ix_interviews_created_at'))
        batch_op.drop_index(batch_op.f('ix_interviews_candidate_email'))

    op.drop_table('interviews')
    # ### end Alembic commands ###
